### PR TITLE
Gaction_MovieRecommendationSystem_Files

### PR DESCRIPTION
**Pull request by Priyadharshini-07**

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@tamilarasumk731 @InbasasiS Can we move it to Dev branch

**Comment by tamilarasumk731** [comment]
@AkbarHabeeb yes & we can deploy the code(node server) in the cloud. 
CC: @InbasasiS

**Comment by AkbarHabeeb** [comment]
Moving it to dev branch.

**Comment by AkbarHabeeb** [comment]
@priyadevendran79 I couldnt open the node server folder.

**Pull request merged**
